language: android
jdk:
    - oraclejdk7
    - oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
